config/routes.rb
Rails.application.routes.draw do
  root 'pages#top_page'
  get 'myPage', to: 'pages#my_page'

  scope module: 'user' do
    get 'sign_up', to: 'registration#new'
    post 'registration/create', to: 'registration#create'
    delete 'sign_out/:id', to: 'registration#destroy'

    get 'login', to: 'session#new'
    post 'session/create', to: 'session#create'
    get 'logout', to: 'session#destroy'

    resources :tweets, only:[:new,:create, :index, :destroy]
  end

  resources :user, :only => [:index,:show] do
    scope module: 'user' do
      resources :follows, :only => [:create,:destroy]
    end
  end

  resources :articles, :only => [:new,:create,:destroy,:show]
  resources :articles do
    resources :comments, :only => [:create, :destroy]
  end
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy

  mount_uploader :picture, PictureUploader

  validates :title, presence: true
  validates :user_id, presence: true
  validates :contents, presence: true
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  include ArticlesHelper
  before_action :check_signed_in
  helper_method :article

  def show
    @new_comment = current_user.comments.new
  end

  def new
    @article = current_user.articles.new
  end

  def create
    @article = current_user.articles.new(article_params)
    if @article.save
      flash[:alert] = "記事の保存に成功しました"
      redirect_to root_path
    else
      flash.now[:alert] = "記事の保存に失敗しました"
      render :new
    end
  end

  def update
    if article.update(article_params)
      flash[:alert] = "記事の編集に成功しました"
      redirect_to root_path
    else
      flash.now[:alert] = "記事の編集に失敗しました"
      render :edit
    end
  end

  def edit

  end

  def destroy
    if article.destroy
      flash[:alert] = "記事の削除に成功しました"
      redirect_to root_path
    else
      flash.now[:alert] = "記事の削除に失敗しました"
      render :show
    end
  end

  private
    def article_params
        params.require(:article).permit(:title,:contents,:picture,:good)
    end

    def article
      @article ||= Article.find(params[:id])
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def article_own?(article)
    article.user.id == current_user.id
  end
end

app/views/articles/_article_form.html.slim
= form_for article do |f|
  p タイトル
  = f.text_area :title
  p 内容
  = f.text_area :contents
  p 写真
  = f.file_field :picture
  br
  = f.submit

app/views/articles/_index.html.slim
h2 記事一覧
br/
- if @articles.blank?
  p 記事がありません
- else
  - @articles.each do |article|
    .field
      .click
        = link_to article_path(article) do
          p = article.title
  = will_paginate @articles, :param_name => 'article_page',:previous_label => ' &lt 前へ', :next_label => '次へ &gt'

app/views/articles/edit.html.slim
h1 ブログの編集
= render partial: 'articles/article_form', locals: {url: article_path,submit_button: 'views.articles.edit.form.submit'}

app/views/articles/new.html.slim
h1 ブログの作成
= render partial: 'articles/article_form', locals: {article: @article, url: articles_path}

app/views/articles/show.html.slim
.user_area
  - if article_own?(article)
    = link_to myPage_path do
      = article.user.name
  - else
    = link_to user_path(article.user.id) do
      = article.user.name

.article_area
  p タイトル
  = article.title
  p 内容
  = article.contents
  - if article.picture?
    p 写真
    = image_tag article.picture_url

- if article_own?(article)
  = button_to "編集する", {:action => "edit"}, :method => :get
  = button_to "削除する", {:action => "destroy"}, :method => :delete

.comment_area
  h2 コメント一覧
  - article.comments.each do |comment|
    .comments
      p = comment.user.name
      p = comment.body
      p ----------
      - if comment_own?(comment)
        = button_to "削除する", [article, comment], :method => :delete

  - unless article.user_id == session[:user_id]
    = form_for [article, @new_comment] do |f|
      = f.text_area :body
      = f.hidden_field :article_id, :value => params[:id]
      br/
      = f.submit 'コメントする'