config/routes.rb
Rails.application.routes.draw do
  root 'pages#top_page'
  get 'myPage', to: 'pages#my_page'

  scope module: 'user' do
    get 'sign_up', to: 'registration#new'
    post 'registration/create', to: 'registration#create'
    delete 'sign_out/:id', to: 'registration#destroy'

    get 'login', to: 'session#new'
    post 'session/create', to: 'session#create'
    get 'logout', to: 'session#destroy'

    resources :tweets, only:[:new,:create, :index, :destroy]
  end

  resources :user, :only => [:index,:show] do
    scope module: 'user' do
      resources :follows, :only => [:create,:destroy]
    end
  end

  resources :articles, :only => [:new,:create,:destroy,:show]
  resources :articles do
    resources :comments, :only => [:create, :destroy]
  end
end

app/views/pages/myPage.html.slim
h2 自分のつぶやき
- @tweets.each do |tweet|
  - unless tweet.reply_id == nil
    p reply
  p = tweet.contents
  = button_to "つぶやきを削除する", tweet_path(tweet.id), :method => :delete
  p -------

h2 自分の投稿
- @article.each do |articles|
  .field
    .click
      = link_to article_path(articles.id) do
        p = articles.title

app/views/pages/my_page.html.slim
h2 自分のつぶやき
- @tweets.each do |tweet|
  - if tweet.reply_id.present?
    p reply
  p = tweet.contents
  = button_to "つぶやきを削除する", tweet_path(tweet), :method => :delete
  p -------

h2 自分の投稿
- @article.each do |articles|
  .field
    .click
      = link_to article_path(articles.id) do
        p = articles.title

app/views/pages/topPage.html.slim
h1 topPage
br/
= render "user/tweets/index"
br/
= render "articles/index"
br/

app/views/pages/top_page.html.slim
h1 topPage
br/
= render "user/tweets/index"
br/
= render "articles/index"
br/