config/routes.rb
Rails.application.routes.draw do
  root 'pages#top_page'
  get 'myPage', to: 'pages#my_page'

  scope module: 'user' do
    get 'sign_up', to: 'registration#new'
    post 'registration/create', to: 'registration#create'
    delete 'sign_out/:id', to: 'registration#destroy'

    get 'login', to: 'session#new'
    post 'session/create', to: 'session#create'
    get 'logout', to: 'session#destroy'

    resources :tweets, only:[:new,:create, :index, :destroy]
  end

  resources :user, :only => [:index,:show] do
    scope module: 'user' do
      resources :follows, :only => [:create,:destroy]
    end
  end

  resources :articles, :only => [:new,:create,:destroy,:show]
  resources :articles do
    resources :comments, :only => [:create, :destroy]
  end
end

app/views/layouts/_header.html.slim
.menu
  - if login_check
    = button_to "topへ", root_path , :class => 'button', :method => :get
    = button_to "記事を投稿する", new_article_path,:class => 'button', :method => :get
    = button_to "つぶやく", new_tweet_path,:class => 'button', :method => :get
    = button_to "ログアウトする", logout_path, :class => 'button', :method => :get
  - else
    = button_to "アカウント登録", sign_up_path,:class => 'button', :method => :get
    = button_to "ログイン", login_path,:class => 'button', :method => :get

app/views/layouts/application.html.slim
doctype html
html
  head
    title BlogWriteApp
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body
    = render "layouts/header"
    = yield